// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <functional>

namespace textsort {

enum class SortOrder : int {
    ASCENDING,
    DESCENDING,
    RANDOM,
};

}  // namespace textsort

namespace std {

template <>
struct hash<::textsort::SortOrder> {
    size_t operator()(::textsort::SortOrder type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
