// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <memory>
#include <mylib/context.hpp>

namespace textsort {

class TextboxListener;
enum class sort_order;
struct ItemList;

class SortItems {
public:
    virtual ~SortItems() {}

    /** For the iOS / Android demo */
    virtual void sort(sort_order order, const ItemList & items) = 0;

    static std::shared_ptr<SortItems> create_with_listener(const std::shared_ptr<TextboxListener> & listener);

    /** For the localhost / command-line demo */
    static ItemList run_sort(const ItemList & items);

    virtual std::shared_ptr<Context> get_context() = 0;

    virtual void set_context(const std::shared_ptr<Context> & context) = 0;
};

}  // namespace textsort
